"""TensorStudio public Python API."""

from __future__ import annotations

from . import data, dtypes, interchange, math, nn, optim, project, vision
from ._version import __version__
from .dtypes import dtype_of, normalize_dtype, promote_types, result_type
from .grad_mode import is_grad_enabled, no_grad, set_grad_enabled
from .interchange import export_onnx
from .ops import (
    acos,
    argmax,
    argmin,
    asin,
    astype,
    atan,
    avg_pool2d,
    clamp,
    clip,
    concat,
    conv2d,
    cos,
    equal,
    greater,
    greater_equal,
    less,
    less_equal,
    log1p,
    max_pool2d,
    maximum,
    minimum,
    not_equal,
    permute,
    rsqrt,
    sin,
    squeeze,
    stack,
    tan,
    transpose,
    unsqueeze,
    where,
)
from .performance import get_num_threads, performance_info, set_num_threads
from .serialization import load, load_npz, save, save_npz
from .tensor import (
    Tensor,
    arange,
    empty,
    empty_like,
    eye,
    from_numpy,
    full,
    full_like,
    linspace,
    manual_seed,
    ones,
    ones_like,
    rand,
    rand_like,
    randn,
    randn_like,
    tensor,
    zeros,
    zeros_like,
)

__all__ = [
    "Tensor",
    "__version__",
    "acos",
    "argmax",
    "argmin",
    "arange",
    "asin",
    "astype",
    "atan",
    "avg_pool2d",
    "clamp",
    "clip",
    "concat",
    "conv2d",
    "cos",
    "data",
    "dtype_of",
    "dtypes",
    "empty",
    "empty_like",
    "eye",
    "equal",
    "export_onnx",
    "from_numpy",
    "full",
    "full_like",
    "greater",
    "greater_equal",
    "get_num_threads",
    "less",
    "less_equal",
    "interchange",
    "is_grad_enabled",
    "linspace",
    "load",
    "load_npz",
    "log1p",
    "manual_seed",
    "maximum",
    "max_pool2d",
    "minimum",
    "math",
    "nn",
    "no_grad",
    "not_equal",
    "ones",
    "ones_like",
    "optim",
    "permute",
    "performance_info",
    "project",
    "promote_types",
    "rand",
    "rand_like",
    "randn",
    "randn_like",
    "rsqrt",
    "save",
    "save_npz",
    "set_grad_enabled",
    "set_num_threads",
    "sin",
    "stack",
    "squeeze",
    "tan",
    "tensor",
    "transpose",
    "unsqueeze",
    "normalize_dtype",
    "result_type",
    "vision",
    "where",
    "zeros",
    "zeros_like",
]
