from __future__ import annotations

from typing import Any

import numpy as np

class Tensor:
    requires_grad: bool
    grad: Tensor | None
    shape: tuple[int, ...]
    strides: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    is_contiguous: bool
    T: Tensor
    def numpy(self) -> np.ndarray: ...
    def tolist(self) -> Any: ...
    def item(self) -> Any: ...
    def clone(self) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def reshape(self, *shape: Any) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    def sum(self, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def mean(self, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def max(self, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def min(self, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def tanh(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def log1p(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def rsqrt(self) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def tan(self) -> Tensor: ...
    def asin(self) -> Tensor: ...
    def acos(self) -> Tensor: ...
    def atan(self) -> Tensor: ...
    def abs(self) -> Tensor: ...
    def clamp(self, min_value: float, max_value: float) -> Tensor: ...
    def clip(self, min_value: float, max_value: float) -> Tensor: ...
    def astype(self, dtype: str) -> Tensor: ...
    def to(self, dtype: str) -> Tensor: ...
    def backward(self, gradient: Tensor | None = None) -> None: ...
    def zero_grad(self) -> None: ...
    def _assign(self, other: Tensor) -> None: ...
    def _add_scaled_(self, other: Tensor, scale: float) -> None: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __radd__(self, other: Any) -> Tensor: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __rsub__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __rmul__(self, other: Any) -> Tensor: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __rtruediv__(self, other: Any) -> Tensor: ...
    def __eq__(self, other: Any) -> Tensor: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> Tensor: ...  # type: ignore[override]
    def __lt__(self, other: Any) -> Tensor: ...
    def __le__(self, other: Any) -> Tensor: ...
    def __gt__(self, other: Any) -> Tensor: ...
    def __ge__(self, other: Any) -> Tensor: ...
    def __iadd__(self, other: Any) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __pow__(self, exponent: float) -> Tensor: ...
    def __matmul__(self, other: Any) -> Tensor: ...
    def __rmatmul__(self, other: Any) -> Tensor: ...


class TensorStudioError(RuntimeError): ...
class ShapeError(TensorStudioError): ...
class DTypeError(TensorStudioError): ...
class DeviceError(TensorStudioError): ...
class AutogradError(TensorStudioError): ...

def tensor(data: Any, dtype: str | None = None, requires_grad: bool = False) -> Tensor: ...
def from_numpy(array: np.ndarray, requires_grad: bool = False) -> Tensor: ...
def zeros(shape: Any, dtype: str = "float32") -> Tensor: ...
def ones(shape: Any, dtype: str = "float32") -> Tensor: ...
def empty(shape: Any, dtype: str = "float32") -> Tensor: ...
def full(shape: Any, fill_value: float, dtype: str = "float32") -> Tensor: ...
def rand(shape: Any, dtype: str = "float32", seed: int | None = None) -> Tensor: ...
def randn(shape: Any, dtype: str = "float32", seed: int | None = None) -> Tensor: ...
def arange(
    start: float,
    stop: float | None = None,
    step: float = 1,
    dtype: str = "float32",
) -> Tensor: ...
def eye(n: int, m: int | None = None, dtype: str = "float32") -> Tensor: ...
def linspace(start: float, stop: float, steps: int, dtype: str = "float32") -> Tensor: ...
def manual_seed(seed: int) -> None: ...
def promote_types(left: str, right: str) -> str: ...
def add(left: Tensor, right: Any) -> Tensor: ...
def sub(left: Tensor, right: Any) -> Tensor: ...
def mul(left: Tensor, right: Any) -> Tensor: ...
def div(left: Tensor, right: Any) -> Tensor: ...
def equal(left: Tensor, right: Any) -> Tensor: ...
def not_equal(left: Tensor, right: Any) -> Tensor: ...
def less(left: Tensor, right: Any) -> Tensor: ...
def less_equal(left: Tensor, right: Any) -> Tensor: ...
def greater(left: Tensor, right: Any) -> Tensor: ...
def greater_equal(left: Tensor, right: Any) -> Tensor: ...
def neg(input: Tensor) -> Tensor: ...
def pow(input: Tensor, exponent: float) -> Tensor: ...
def matmul(left: Tensor, right: Any) -> Tensor: ...
def conv2d(
    input: Tensor,
    weight: Tensor,
    bias: Tensor | None = None,
    stride_h: int = 1,
    stride_w: int = 1,
    padding_h: int = 0,
    padding_w: int = 0,
    dilation_h: int = 1,
    dilation_w: int = 1,
) -> Tensor: ...
def max_pool2d(
    input: Tensor,
    kernel_h: int,
    kernel_w: int,
    stride_h: int = 1,
    stride_w: int = 1,
    padding_h: int = 0,
    padding_w: int = 0,
    dilation_h: int = 1,
    dilation_w: int = 1,
) -> Tensor: ...
def avg_pool2d(
    input: Tensor,
    kernel_h: int,
    kernel_w: int,
    stride_h: int = 1,
    stride_w: int = 1,
    padding_h: int = 0,
    padding_w: int = 0,
    count_include_pad: bool = False,
) -> Tensor: ...
def sum(input: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
def mean(input: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
def max(input: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
def min(input: Tensor, axis: int | None = None, keepdims: bool = False) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def log1p(input: Tensor) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def rsqrt(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def tan(input: Tensor) -> Tensor: ...
def asin(input: Tensor) -> Tensor: ...
def acos(input: Tensor) -> Tensor: ...
def atan(input: Tensor) -> Tensor: ...
def abs(input: Tensor) -> Tensor: ...
def clamp(input: Tensor, min_value: float, max_value: float) -> Tensor: ...
def astype(input: Tensor, dtype: str) -> Tensor: ...
def concat(tensors: list[Tensor], axis: int = 0) -> Tensor: ...
def stack(tensors: list[Tensor], axis: int = 0) -> Tensor: ...
def reshape(input: Tensor, shape: Any) -> Tensor: ...
def flatten(input: Tensor) -> Tensor: ...
def transpose(input: Tensor) -> Tensor: ...
def backward(output: Tensor, gradient: Tensor | None = None) -> None: ...
def _grad_enabled() -> bool: ...
def _set_grad_enabled(enabled: bool) -> None: ...
