from __future__ import annotations

from typing import Any

import numpy as np

class Tensor:
    requires_grad: bool
    grad: Tensor | None
    shape: tuple[int, ...]
    dtype: str
    ndim: int
    size: int
    T: Tensor
    def numpy(self) -> np.ndarray: ...
    def tolist(self) -> Any: ...
    def item(self) -> Any: ...
    def reshape(self, *shape: Any) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def tanh(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def backward(self, gradient: Tensor | None = None) -> None: ...
    def zero_grad(self) -> None: ...
    def _assign(self, other: Tensor) -> None: ...
    def _add_scaled_(self, other: Tensor, scale: float) -> None: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __radd__(self, other: Any) -> Tensor: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __rsub__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __rmul__(self, other: Any) -> Tensor: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __rtruediv__(self, other: Any) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __pow__(self, exponent: float) -> Tensor: ...
    def __matmul__(self, other: Any) -> Tensor: ...
    def __rmatmul__(self, other: Any) -> Tensor: ...


class TensorStudioError(RuntimeError): ...
class ShapeError(TensorStudioError): ...
class DTypeError(TensorStudioError): ...
class DeviceError(TensorStudioError): ...
class AutogradError(TensorStudioError): ...

def tensor(data: Any, dtype: str | None = None, requires_grad: bool = False) -> Tensor: ...
def from_numpy(array: np.ndarray, requires_grad: bool = False) -> Tensor: ...
def zeros(shape: Any, dtype: str = "float32") -> Tensor: ...
def ones(shape: Any, dtype: str = "float32") -> Tensor: ...
def full(shape: Any, fill_value: float, dtype: str = "float32") -> Tensor: ...
def randn(shape: Any, dtype: str = "float32", seed: int | None = None) -> Tensor: ...
def arange(
    start: float,
    stop: float | None = None,
    step: float = 1,
    dtype: str = "float32",
) -> Tensor: ...
def add(left: Tensor, right: Any) -> Tensor: ...
def sub(left: Tensor, right: Any) -> Tensor: ...
def mul(left: Tensor, right: Any) -> Tensor: ...
def div(left: Tensor, right: Any) -> Tensor: ...
def neg(input: Tensor) -> Tensor: ...
def pow(input: Tensor, exponent: float) -> Tensor: ...
def matmul(left: Tensor, right: Any) -> Tensor: ...
def sum(input: Tensor) -> Tensor: ...
def mean(input: Tensor) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def reshape(input: Tensor, shape: Any) -> Tensor: ...
def flatten(input: Tensor) -> Tensor: ...
def transpose(input: Tensor) -> Tensor: ...
def backward(output: Tensor, gradient: Tensor | None = None) -> None: ...
